# coding: utf-8

"""
    qg_api

    qualys guard rest api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.scan import Scan  # noqa: E501
from swagger_client.rest import ApiException


class TestScan(unittest.TestCase):
    """Scan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScan(self):
        """Test Scan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scan.Scan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
