# coding: utf-8

"""
    qg_api

    qualys guard rest api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.server_findings import ServerFindings  # noqa: E501
from swagger_client.rest import ApiException


class TestServerFindings(unittest.TestCase):
    """ServerFindings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerFindings(self):
        """Test ServerFindings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.server_findings.ServerFindings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
