# coding: utf-8

"""
    qg_api

    qualys guard rest api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.report_api import ReportApi  # noqa: E501
from openapi_client.rest import ApiException


class TestReportApi(unittest.TestCase):
    """ReportApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.report_api.ReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_report(self):
        """Test case for create_report

        Create report  # noqa: E501
        """
        pass

    def test_get_report(self):
        """Test case for get_report

        Get report by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
