# coding: utf-8

"""
    qg_api

    qualys guard rest api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.admin_api import AdminApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_action(self):
        """Test case for admin_action

        for admin actions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
