# coding: utf-8

"""
    qg_api

    qualys guard rest api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.admin_api import AdminApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_action(self):
        """Test case for admin_action

        for admin actions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
