# coding: utf-8

"""
    qg_api

    qualys guard rest api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.vulner import Vulner  # noqa: E501
from swagger_client.rest import ApiException


class TestVulner(unittest.TestCase):
    """Vulner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVulner(self):
        """Test Vulner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vulner.Vulner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
