# coding: utf-8

"""
    qg_api

    qualys guard rest api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.scan_api import ScanApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScanApi(unittest.TestCase):
    """ScanApi unit test stubs"""

    def setUp(self):
        self.api = api.scan_api.ScanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_scan(self):
        """Test case for create_scan

        Create scan  # noqa: E501
        """
        pass

    def test_get_scan(self):
        """Test case for get_scan

        Get user by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
