# coding: utf-8

# flake8: noqa
"""
    qg_api

    qualys guard rest api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.patch import Patch
from openapi_client.models.report import Report
from openapi_client.models.scan import Scan
from openapi_client.models.server import Server
from openapi_client.models.vulner import Vulner
