# coding: utf-8

# flake8: noqa
"""
    qg_api

    qualys guard rest api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.patch import Patch
from swagger_client.models.report import Report
from swagger_client.models.scan import Scan
from swagger_client.models.server import Server
from swagger_client.models.server_findings import ServerFindings
from swagger_client.models.vulner import Vulner
