# coding: utf-8

# flake8: noqa

"""
    qg_api

    qualys guard rest api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.admin_api import AdminApi
from openapi_client.api.report_api import ReportApi
from openapi_client.api.scan_api import ScanApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.patch import Patch
from openapi_client.models.report import Report
from openapi_client.models.scan import Scan
from openapi_client.models.server import Server
from openapi_client.models.vulner import Vulner

